[phases.setup]
# Defina o diretório onde seu backend está
workdir = "backend"

[phases.install]
# Instale as dependências no diretório backend
run = "npm install"

[phases.build]
# Comando de build (se aplicável)
run = "npm run build"

[phases.start]
# Comando para iniciar o servidor
run = "npm start"
